server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: core-service

  datasource:
    url: jdbc:postgresql://localhost:5440/fitness_core
    username: fitness_user
    password: fitness_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.core-changelog-master.yaml
    enabled: true

  kafka:
    topic-client: ${KAFKA_CLIENT_TOPIC:clients.status}
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}

logging:
  level:
    com.fitness.core: DEBUG
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG